version: "3.8"
services:
  backend-php:
    image: php:8.3-cli
    container_name: backend-php
    build:
      context: ./ 
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html  # Monta la carpeta 'backend' dentro del contenedor
    ports:
      - "8000:80"
    networks:
      - backend_mailhog_network

  mailhog:
    image: mailhog/mailhog
    container_name: backend-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend_mailhog_network

networks:
  backend_mailhog_network:
    driver: bridge
